version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - ./cache:/data

    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379

volumes:
  cache:
    driver: local
